{{- if .Values.ExternalSecret.enabled -}}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "postgresql-backups.fullname" . }}
spec:
  backendType: systemManager
  data:
    {{- if .Values.ExternalSecret.Envs }}
    {{ toYaml .Values.ExternalSecret.Envs | nindent 12 }}
    {{- end }}
{{- end }}
