apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    secret.reloader.stakater.com/reload: "wp"
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        co.elastic.metrics/module: apache
        co.elastic.metrics/hosts: '${data.host}:80'
        co.elastic.logs/module: apache
        co.elastic.logs/fileset.stdout: access
        co.elastic.logs/fileset.stderr: error
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:5.4.2-apache
        name: wordpress
        envFrom:
        - secretRef:
            name: wp
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress

  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: wp.maddevs.org
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress
          servicePort: 80
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: wp
spec:
  backendType: systemManager
#  roleArn: 
  data:
    - key: /wp/database/username
      name: WORDPRESS_DB_USER
    - key: /wp/database/password
      name: WORDPRESS_DB_PASSWORD
    - key: /wp/database/database
      name: WORDPRESS_DB_NAME
    - key: /wp/database/address
      name: WORDPRESS_DB_HOST